### ISSUE TITLE
Spaces in Directory Names Causes Program to Crash

### ISSUE THREAD

**Issue by QuietCoderBoi** [QuietCoderBoi/Python-Bank-Project#1]
This is incredibly hard to identify but since Requirements.txt is not being generated it's safe to assume that pipreqs does not get the correct directory. This is most likely due to the command being passed to the subprocess being split on " " characters (as per default split behaviour). Further testing will need to be done to confirm this but that's the most likely theory.
```Traceback (most recent call last):
  File "C:\Users\Connor\Desktop\Bank Thing\Bank.py", line 39, in <module>
    with open("Requirements.txt", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Requirements.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Connor\Desktop\Bank Thing\Bank.py", line 62, in <module>
    with open("Requirements.txt", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Requirements.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Connor\Desktop\Bank Thing\Bank.py", line 65, in <module>
    if len(required_pip_modules) > 0:
NameError: name 'required_pip_modules' is not defined```

**Comment by QuietCoderBoi** [comment]
Fixed 11/04/21 - 04:10
